apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kbot
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/szdobnikova-code/kbot
  ref:
    branch: develop
